"""Initial schema

Revision ID: 68a5552169c4
Revises: 
Create Date: 2026-07-16 12:19:58.793261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a5552169c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threatevent',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('target_system', sa.String(), nullable=True),
    sa.Column('target_object', sa.String(), nullable=True),
    sa.Column('bytes_transferred', sa.Integer(), nullable=True),
    sa.Column('command_text', sa.String(), nullable=True),
    sa.Column('result_status', sa.String(), nullable=True),
    sa.Column('composite_risk_score', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('rule_score', sa.Float(), nullable=True),
    sa.Column('risk_band', sa.String(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threatevent_session_id'), 'threatevent', ['session_id'], unique=False)
    op.create_index(op.f('ix_threatevent_timestamp'), 'threatevent', ['timestamp'], unique=False)
    op.create_index(op.f('ix_threatevent_username'), 'threatevent', ['username'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_threatevent_username'), table_name='threatevent')
    op.drop_index(op.f('ix_threatevent_timestamp'), table_name='threatevent')
    op.drop_index(op.f('ix_threatevent_session_id'), table_name='threatevent')
    op.drop_table('threatevent')
    # ### end Alembic commands ###
